apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    isDefault: false
    editable: true

  - name: InfluxDB-Coupon
    type: influxdb
    access: proxy
    database: k6_coupon
    url: http://influxdb:8086
    isDefault: true
    editable: true